name: Upstream Sync

on:
  schedule:
    - cron: "0 0 * * *" # 每天同步一次
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git committer identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: love-Liushuang/NotionNextStorage
          ref: main

      - name: Add upstream source repository
        run: |
          git remote add upstream https://github.com/love-Liushuang/NotionNext.git
          git fetch upstream

      - name: Sync updates from upstream
        run: |
          git checkout -b sync-updates
          # 合并上游代码时，使用 "ours" 策略保留本地文件
          git merge -X ours upstream/main --allow-unrelated-histories --no-edit || true

      - name: Push updates to a new branch
        run: |
          git push origin sync-updates

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync updates from upstream"
          branch: sync-updates
          base: main
          title: "Sync updates from upstream"
          body: |
            This Pull Request contains updates from the upstream repository.
            Please review and merge if all checks pass.